# Generated by Django 6.1 on 2026-08-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_gamehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='icon_character',
            field=models.CharField(default='學', help_text='Nhập 1 chữ Hán (VD: 啓, 練, 達)', max_length=5, verbose_name='Ký tự Ấn chương'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subtitle',
            field=models.CharField(default='GIÁO TRÌNH TIÊU CHUẨN', help_text='VD: NHẬP MÔN CƠ BẢN', max_length=100, verbose_name='Mục tiêu học tập'),
        ),
    ]
