# Generated by Django 6.1 on 2026-08-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_curriculum_icon_character_curriculum_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='name',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='curriculum_images/', verbose_name='Ảnh bìa'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='title',
            field=models.CharField(default='Giáo trình tạm', max_length=200, verbose_name='Tên giáo trình'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
    ]
