# Generated by Django 6.1 on 2026-08-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_curriculum_name_curriculum_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='title',
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả ngắn'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_hanzi',
            field=models.CharField(default='Tạm', help_text='VD: AI小语,你好!', max_length=200, verbose_name='Tiêu đề (Chữ Hán)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_pinyin',
            field=models.CharField(blank=True, help_text='VD: AI Xiǎoyǔ, nǐ hǎo!', max_length=200, null=True, verbose_name='Tiêu đề (Pinyin)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_vietnamese',
            field=models.CharField(default='Tạm', help_text='VD: Xin chào AI Tiểu Ngữ!', max_length=200, verbose_name='Tiêu đề (Tiếng Việt)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Số thứ tự bài'),
        ),
    ]
