# Generated by Django 6.1 on 2026-08-18 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_lesson_title_lesson_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên đề thi')),
                ('hsk_level', models.IntegerField(default=1, verbose_name='Cấp độ HSK')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='Thời gian làm bài (phút)')),
                ('listening_audio', models.FileField(blank=True, null=True, upload_to='exam_audios/', verbose_name='File Audio phần Nghe')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả đề thi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(verbose_name='Số thứ tự câu hỏi')),
                ('section_type', models.CharField(choices=[('listening', 'Nghe hiểu'), ('reading', 'Đọc hiểu')], max_length=50, verbose_name='Phần thi')),
                ('question_group', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nhóm câu hỏi')),
                ('shared_image', models.ImageField(blank=True, null=True, upload_to='exam_images/shared/', verbose_name='Ảnh dùng chung (A-F)')),
                ('passage_text', models.TextField(blank=True, null=True, verbose_name='Đoạn văn dùng chung (Chữ Hán)')),
                ('passage_pinyin', models.TextField(blank=True, null=True, verbose_name='Đoạn văn dùng chung (Pinyin)')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Câu hỏi (Chữ Hán)')),
                ('content_pinyin', models.TextField(blank=True, null=True, verbose_name='Câu hỏi (Pinyin)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exam_images/', verbose_name='Hình ảnh đính kèm câu hỏi')),
                ('option_a', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đáp án A (Chữ)')),
                ('option_a_pinyin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đáp án A (Pinyin)')),
                ('option_b', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đáp án B (Chữ)')),
                ('option_b_pinyin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đáp án B (Pinyin)')),
                ('option_c', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đáp án C (Chữ)')),
                ('option_c_pinyin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đáp án C (Pinyin)')),
                ('option_d', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đáp án D')),
                ('option_e', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đáp án E')),
                ('option_f', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đáp án F')),
                ('correct_answer', models.CharField(max_length=5, verbose_name='Đáp án đúng (A/B/C/D/E/F)')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Giải thích chi tiết')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.exam', verbose_name='Thuộc đề thi')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Điểm số đạt được')),
                ('total_correct', models.IntegerField(verbose_name='Số câu đúng')),
                ('time_spent', models.IntegerField(verbose_name='Thời gian làm bài (giây)')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.exam', verbose_name='Đề thi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Học viên')),
            ],
        ),
    ]
