# Generated by Django 6.1 on 2026-08-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_exam_examquestion_examresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='user_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
